"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from "react";
import {roboto} from "@/app/_lib/font";
import QueryClientProvider from "@/app/_lib/query_client.provider"
import ReactSessionProvider from "@/app/_lib/session.provider";

const inter = Inter({ subsets: ['latin'] })

/*export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default async function RootLayout({
                                             children ,
                                         }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={` font-sans dark no-scrollbar `}>
        <ReactSessionProvider>
            <QueryClientProvider>
                {children}
            </QueryClientProvider>
        </ReactSessionProvider>
        </body>
        </html>
    )
}
