import type { Metadata } from 'next'
import './globals.css'
import React from "react";
import {roboto} from "@/app/_lib/font";
import QueryClientProvider from "@/app/_lib/query_client.provider"
import SessionProvider from "@/app/_lib/session.provider";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
                                             children ,
                                         }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${roboto.className} font-sans  dark:bg-background no-scrollbar `}>
            <QueryClientProvider>
                <SessionProvider>
                    {children}
                </SessionProvider>
            </QueryClientProvider>
        </body>
        </html>
    )
}
